//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Role_Autorisations
    {
        public int id_Application_role_aut { get; set; }
        public Nullable<int> id_Application { get; set; }
        public Nullable<int> id_utilisateur_role { get; set; }
        public Nullable<int> id_autorisation { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Autorisation Autorisation { get; set; }
        public virtual Utilisateur_Role Utilisateur_Role { get; set; }
    }
}
