//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Permissions
    {
        public int id_utilisateur { get; set; }
        public string nom_utilisateur { get; set; }
        public string nom_role { get; set; }
        public string nom_autorisation { get; set; }
        public string nom_application { get; set; }
    }
}
