//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur_Role()
        {
            this.Application_Role_Autorisations = new HashSet<Application_Role_Autorisations>();
        }
    
        public int id_utilisateur_role { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
        public Nullable<int> id_role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Role_Autorisations> Application_Role_Autorisations { get; set; }
        public virtual Role Role { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
