server:
  port: 9999

spring:
  application:
    name: gateway-serv

  cloud:
    config:
      enabled: false

    discovery:
      enabled: true

    gateway:
      server:
        webmvc:
          routes:
            - id: courses-route
              uri: lb://course-serv
              predicates:
                - Path=/api/courses,/api/courses/**

            - id: students-route
              uri: lb://student-serv
              predicates:
                - Path=/api/students,/api/students/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true